# Generated by Django 2.1.15 on 2020-07-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberKillChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recon', models.TextField()),
                ('weapon', models.TextField()),
                ('delivery', models.TextField()),
                ('exploitation', models.TextField()),
                ('installation', models.TextField()),
                ('command_and_control', models.TextField()),
                ('exfiltration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('sotto_titolo', models.CharField(default=None, max_length=120)),
                ('docker_name', models.CharField(max_length=120)),
                ('descrizione', models.TextField()),
                ('cap_add', models.CharField(choices=[('NET_ADMIN', 'Net Admin')], default='NET_ADMIN', max_length=32)),
                ('detach', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=32)),
                ('auto_remove', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=120)),
                ('cognome', models.CharField(max_length=120)),
                ('username', models.CharField(error_messages={'unique': 'Username già utilizzato'}, max_length=120, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('professione', models.CharField(max_length=120)),
                ('email', models.EmailField(error_messages={'unique': 'Email già utilizzata'}, max_length=120, unique=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
