# Generated by Django 2.1.15 on 2020-07-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cognome', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('professione', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
