# Generated by Django 2.1.15 on 2020-08-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200804_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='livello',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livello_diff', to='app.Tag_Level'),
        ),
    ]
