# Generated by Django 2.1.15 on 2020-08-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lab_livello'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_args',
            name='spiegazione',
            field=models.TextField(default=''),
        ),
    ]
