# Generated by Django 2.1.15 on 2020-08-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tag_args_spiegazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberkillchain',
            name='intro',
            field=models.TextField(default=''),
        ),
    ]
