# Generated by Django 2.1.15 on 2020-07-25 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200725_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberKillChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recon', models.TextField()),
                ('weapon', models.TextField()),
                ('delivery', models.TextField()),
                ('exploitation', models.TextField()),
                ('installation', models.TextField()),
                ('command_and_control', models.TextField()),
                ('exfiltration', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='docker_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
