# Generated by Django 2.1.15 on 2020-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cyberkillchain_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='documentazione',
            field=models.TextField(default=''),
        ),
    ]
