# Generated by Django 2.1.15 on 2020-08-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lab_documentazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='porta_vpn',
            field=models.TextField(default='', max_length=120),
        ),
    ]
