# Generated by Django 2.1.15 on 2020-09-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_porta_vpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='porta_vpn',
            field=models.TextField(default='', max_length=10),
        ),
    ]
