# Generated by Django 2.1.15 on 2020-09-07 10:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_id_ctfd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTFd_configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_API', models.CharField(max_length=220)),
                ('token_API', models.CharField(max_length=64)),
                ('port_API', models.IntegerField(default=8000, validators=[app.models.validate_flag])),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='categoria',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lab',
            name='flag',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AddField(
            model_name='lab',
            name='valore_flag',
            field=models.IntegerField(default=10, validators=[app.models.validate_flag]),
        ),
    ]
