# Generated by Django 2.1.15 on 2020-09-07 10:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200907_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfd_configs',
            name='port_API',
            field=models.IntegerField(default=8000, validators=[app.models.validate_flag]),
        ),
        migrations.AlterField(
            model_name='lab',
            name='valore_flag',
            field=models.IntegerField(default=10, validators=[app.models.validate_flag]),
        ),
    ]
