# Generated by Django 2.1.15 on 2020-09-14 17:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200907_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHTunnel_configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FULL_PATH_SSH_KEY', models.CharField(max_length=220)),
                ('USER_SERVER', models.CharField(max_length=64)),
                ('DNS_NAME_SERVER', models.CharField(max_length=220)),
                ('LOCAL_PORT', models.IntegerField(validators=[app.models.validate_flag])),
                ('REMOTE_PORT', models.IntegerField(validators=[app.models.validate_flag])),
            ],
        ),
        migrations.AlterField(
            model_name='lab',
            name='categoria',
            field=models.CharField(default='', max_length=120, verbose_name='Categoria della challenge'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='valore_flag',
            field=models.IntegerField(default=10, validators=[app.models.validate_flag], verbose_name='Punteggio della flag'),
        ),
    ]
