# Generated by Django 2.1.15 on 2020-09-18 08:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200914_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='hint',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='hint_cost',
            field=models.IntegerField(blank=True, default=4, null=True, validators=[app.models.validate_flag], verbose_name='Costo del Hint'),
        ),
    ]
