# Generated by Django 2.1.15 on 2020-09-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200918_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshtunnel_configs',
            name='DNS_NAME_SERVER',
        ),
        migrations.RemoveField(
            model_name='sshtunnel_configs',
            name='FULL_PATH_SSH_KEY',
        ),
        migrations.RemoveField(
            model_name='sshtunnel_configs',
            name='LOCAL_PORT',
        ),
        migrations.RemoveField(
            model_name='sshtunnel_configs',
            name='REMOTE_PORT',
        ),
        migrations.RemoveField(
            model_name='sshtunnel_configs',
            name='USER_SERVER',
        ),
    ]
