# Generated by Django 2.1.15 on 2020-09-21 07:52

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200918_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_avviati', models.IntegerField(default=0, validators=[app.models.validate_flag])),
                ('flag_trovate', models.IntegerField(default=0, validators=[app.models.validate_flag])),
                ('guide_lette', models.IntegerField(default=0, validators=[app.models.validate_flag])),
                ('user_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_stat', to='app.User')),
            ],
        ),
    ]
