# Generated by Django 2.1.15 on 2020-09-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_statistiche_punteggio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctfd_configs',
            options={'verbose_name': 'Configurazione per la connessione CTFd', 'verbose_name_plural': 'Configurazione per la connessione CTFd'},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': 'Laboratori', 'verbose_name_plural': 'Laboratori'},
        ),
        migrations.AlterModelOptions(
            name='notifica',
            options={'verbose_name': 'Notifiche', 'verbose_name_plural': 'Notifiche'},
        ),
        migrations.AlterModelOptions(
            name='sshtunnel_configs',
            options={'verbose_name': 'Configurazione per la connessione alla macchina Docker', 'verbose_name_plural': 'Configurazione per la connessione alla macchina Docker'},
        ),
        migrations.AlterModelOptions(
            name='statistiche',
            options={'verbose_name': "Statistiche dell'utente", 'verbose_name_plural': "Statistiche dell'utente"},
        ),
        migrations.AlterModelOptions(
            name='tag_args',
            options={'verbose_name': 'Argomenti per laboratori', 'verbose_name_plural': 'Argomenti per laboratori'},
        ),
        migrations.AlterModelOptions(
            name='tag_level',
            options={'verbose_name': 'Livelli di difficoltà per laboratori', 'verbose_name_plural': 'Livelli di difficoltà per laboratori'},
        ),
        migrations.AddField(
            model_name='user',
            name='pwd_ctfd',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='notifica',
            name='destinatario',
            field=models.CharField(help_text="Inserire l'id dell utente, per mandare singolarmente una notifica a quell'utente, oppure la parola 'tutti' per mandarla a tutti gli utenti", max_length=50),
        ),
        migrations.AlterField(
            model_name='tag_args',
            name='colore',
            field=models.CharField(help_text='Inserire un colore esadecimale, esempio: #DCB50A', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='tag_level',
            name='colore',
            field=models.CharField(help_text='Inserire un colore esadecimale, esempio: #DCB50A', max_length=7, unique=True),
        ),
    ]
