# Generated by Django 2.1.15 on 2020-09-25 19:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_lab_durata_secondi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='durata_secondi',
            field=models.IntegerField(default=3600, help_text='Esempio: 3600 secondi sono 1 ora, 300 secondi sono 5 minuti', validators=[app.models.validate_flag], verbose_name='Durata massima in secondi'),
        ),
    ]
